### ISSUE TITLE
Navigation impressum.html

### ISSUE THREAD

**Issue by GerKev-HO** [GerKev-SI/ECHomepage#24]
Wenn man auf Impressum Seite ist und direkt zurück zur Kalender section will dann geht das über Navigation in Kopfzeile nicht.

**Comment by kellergoech** [comment]
Also hab es mir mal angeschaut, die links passen auf der Browseransicht geht es auch - die erste idee wäre jetzt das menü auf dem handy ganz rauszulassen, dass man da nur auf die webseite gesamt zurück kann.

**Comment by kellergoech** [comment]
Hab mal mit #30   einen Versuch drinnen wo die Meüanzeigen nur noch im Browser da sind, beim Handy kommt man dann nur noch auf die hauptseite zurück, müsste man mal schauen ob das so passt.
